# Generated by Django 5.0.3 on 2024-04-04 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('fio', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=50, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_newsletter', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время первой рассылки')),
                ('last_newsletter', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней рассылки')),
                ('periodicity', models.CharField(choices=[('Раз в день', 'Daily'), ('Раз в неделю', 'Weekly'), ('Раз в месяц', 'Monthly')], max_length=20, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('завершена', 'Finished'), ('создана', 'Created'), ('запущена', 'Launched')], default='создана', max_length=20, verbose_name='Статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.message', verbose_name='Сообщения')),
            ],
        ),
    ]
