# Generated by Django 4.2 on 2024-05-14 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_clients_client_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.newsletter', verbose_name='Название рассылки'),
        ),
    ]
