# Generated by Django 4.2 on 2024-05-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_client_owner_logs_user_newsletter_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('view_all_newsletters', 'Can view all newsletters'), ('view_user_list', 'Can view user list'), ('block_user', 'Can block users'), ('deactivate_newsletter', 'Can deactivate newsletters')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
